pipeline {
  agent {
    kubernetes {
      inheritFrom 'nodejs base'
      containerTemplate {
        name 'nodejs'
        image 'node:16.14.0'
      }
    }
  }

  environment {
        GITHUB_CREDENTIAL_ID = 'github-id'
        AWS_IAM_CREDENTIAL_ID_DEV = 'aws-iam-id-dev'
        AWS_IAM_CREDENTIAL_ID_TEST = 'aws-iam-id-test'
        AWS_ECR_CREDENTIAL_ID_DEV = 'aws-ecr-id-dev'
        AWS_ECR_CREDENTIAL_ID_TEST = 'aws-ecr-id-test'
        DEV_KUBECONFIG_CREDENTIAL_ID = 'fedml-dev-kubeconfig'
        TEST_KUBECONFIG_CREDENTIAL_ID = 'fedml-test-kubeconfig'

        AWS_IAM_CREDENTIAL_ID_PRODUCTION = 'aws-iam-id-release'
        AWS_ECR_CREDENTIAL_ID_PRODUCTION = 'aws-ecr-id-release'
        PRODUCTION_KUBECONFIG_CREDENTIAL_ID = 'fedml-release-kubeconfig'

        REGISTRY_DEV = '276355461497.dkr.ecr.us-west-1.amazonaws.com'
        REGISTRY_TEST = '616844723618.dkr.ecr.us-west-2.amazonaws.com'
        HTTPS_REGISTRY_DEV = 'https://276355461497.dkr.ecr.us-west-1.amazonaws.com'
        HTTPS_REGISTRY_TEST = 'https://616844723618.dkr.ecr.us-west-1.amazonaws.com'
        AWS_REGION_NAME_DEV = 'us-west-1'
        AWS_REGION_NAME_TEST = 'us-west-2'
        DEPLOY_NAMESPACE_DEV = 'fedml-devops-dev'
        DEPLOY_NAMESPACE_TEST = 'fedml-devops-test'
        VERSION_DEV = 'dev'
        VERSION_TEST = 'test'
        BRANCH_DEV = 'dev'
        BRANCH_TEST = 'test'

        REGISTRY_PRODUCTION = '276355461497.dkr.ecr.us-west-1.amazonaws.com'
        HTTPS_REGISTRY_PRODUCTION = 'https://276355461497.dkr.ecr.us-west-1.amazonaws.com'
        AWS_REGION_NAME_PRODUCTION = 'us-west-1'
        DEPLOY_NAMESPACE_PRODUCTION = 'fedml-devops-release'
        VERSION_PRODUCTION = 'release'
        BRANCH_PRODUCTION = 'main'

        DOCKER_NAMESPACE = ''
        APP_NAME = 'fedml-official-web'
        DEPLOY_NAME = 'fedml-official-web'
        GIT_URL = 'https://github.com/FedML-Inc/FedML-Official-Website.git'
        SONAR_HOST = ''
        SONAR_CREDENTIAL_ID = 'sonar-token'
        TAG_NAME = "SNAPSHOT-$BUILD_NUMBER"
        FEDML_MAIL_SUCCESS_SUBJECT = 'FedMLDevOPS Succeeded Pipeline'
        FEDML_MAIL_FAILURE_SUBJECT = 'FedMLDevOPS Failed Pipeline'
        FEDML_MAIL_BODY1 = "Build Display Name: "
        FEDML_MAIL_BODY2 = ", Please check build details by the following URL: http://kube.fedml.ai/workspaces/fedml-devops-services/devops"
    }

  stages {
    stage('checkout for dev') {
      when {
        branch env.BRANCH_DEV
      }
      agent none
      steps {
        git(branch: env.BRANCH_DEV, url: env.GIT_URL, credentialsId: env.GITHUB_CREDENTIAL_ID, changelog: true, poll: false)
      }
    }

    stage('checkout for test') {
      when {
        branch env.BRANCH_TEST
      }
      agent none
      steps {
        git(branch: env.BRANCH_TEST, url: env.GIT_URL, credentialsId: env.GITHUB_CREDENTIAL_ID, changelog: true, poll: false)
      }
    }

    stage('checkout for production') {
      when {
        branch env.BRANCH_PRODUCTION
      }
      agent none
      steps {
        git(branch: env.BRANCH_PRODUCTION, url: env.GIT_URL, credentialsId: env.GITHUB_CREDENTIAL_ID, changelog: true, poll: false)
      }
    }

    stage('mlops build for dev') {
      when {
        branch env.BRANCH_DEV
      }
      steps {
        container('nodejs') {
          sh 'npm cache clear --force'
          sh 'npm install'
          sh 'yarn build'
        }
      }
    }

    stage('mlops build for test') {
      when {
        branch env.BRANCH_TEST
      }
      steps {
        container('nodejs') {
          sh 'npm install'
          sh 'yarn build'
        }
      }
    }

    stage('mlops build for production') {
      when {
        branch env.BRANCH_PRODUCTION
      }
      steps {
        container('nodejs') {
          sh 'npm install'
          sh 'yarn build'
        }
      }
    }

    stage('docker build for dev') {
      when {
        branch env.BRANCH_DEV
      }
      steps {
        container('base') {
          sh 'docker build --network=host -f ./devops/Dockerfile -t $REGISTRY_DEV/$DOCKER_NAMESPACE$APP_NAME:$VERSION_DEV-SNAPSHOT-$BUILD_NUMBER .'
        }
      }
    }

    stage('docker build for test') {
      when {
        branch env.BRANCH_TEST
      }
      steps {
        container('base') {
          sh 'docker build --network=host -f ./devops/Dockerfile -t $REGISTRY_TEST/$DOCKER_NAMESPACE$APP_NAME:$VERSION_TEST-SNAPSHOT-$BUILD_NUMBER .'
        }
      }
    }

    stage('docker build for production') {
      when {
        branch env.BRANCH_PRODUCTION
      }
      steps {
        container('base') {
          sh 'docker build --network=host -f ./devops/Dockerfile -t $REGISTRY_PRODUCTION/$DOCKER_NAMESPACE$APP_NAME:$VERSION_PRODUCTION-SNAPSHOT-$BUILD_NUMBER .'
        }
      }
    }

    stage('push latest for dev') {
      when {
        branch env.BRANCH_DEV
      }
      steps {
        container('base') {
          withCredentials([usernamePassword(passwordVariable : 'AWS_IAM_ACCESS_ID' ,usernameVariable : 'AWS_ECR_USERNAME' ,credentialsId : "$AWS_ECR_CREDENTIAL_ID_DEV" ,)]) {
             withCredentials([usernamePassword(passwordVariable : 'AWS_IAM_ACCESS_KEY' ,usernameVariable : 'AWS_REGION' ,credentialsId : "$AWS_IAM_CREDENTIAL_ID_DEV" ,)]) {
                sh 'curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"'
                sh 'unzip awscliv2.zip'
                sh './aws/install'
                sh 'chmod a+x ./devops/set-aws-credentials.sh;./devops/set-aws-credentials.sh $AWS_IAM_ACCESS_ID $AWS_IAM_ACCESS_KEY $AWS_REGION'
                sh 'docker login $REGISTRY_DEV -u $AWS_ECR_USERNAME -p $(/usr/local/bin/aws ecr get-login-password --region $AWS_REGION)'
             }
          }
          sh 'docker tag  $REGISTRY_DEV/$DOCKER_NAMESPACE$APP_NAME:$VERSION_DEV-SNAPSHOT-$BUILD_NUMBER $REGISTRY_DEV/$DOCKER_NAMESPACE$APP_NAME:$VERSION_DEV'
          sh 'docker push  $REGISTRY_DEV/$DOCKER_NAMESPACE$APP_NAME:$VERSION_DEV'
        }
      }
    }

    stage('push latest for test') {
      when {
        branch env.BRANCH_TEST
      }
      steps {
        container('base') {
          withCredentials([usernamePassword(passwordVariable : 'AWS_IAM_ACCESS_ID' ,usernameVariable : 'AWS_ECR_USERNAME' ,credentialsId : "$AWS_ECR_CREDENTIAL_ID_TEST" ,)]) {
             withCredentials([usernamePassword(passwordVariable : 'AWS_IAM_ACCESS_KEY' ,usernameVariable : 'AWS_REGION' ,credentialsId : "$AWS_IAM_CREDENTIAL_ID_TEST" ,)]) {
                sh 'curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"'
                sh 'unzip awscliv2.zip'
                sh './aws/install'
                sh 'chmod a+x ./devops/set-aws-credentials.sh;./devops/set-aws-credentials.sh $AWS_IAM_ACCESS_ID $AWS_IAM_ACCESS_KEY $AWS_REGION'
                sh 'docker login $REGISTRY_TEST -u $AWS_ECR_USERNAME -p $(/usr/local/bin/aws ecr get-login-password --region $AWS_REGION)'
             }
          }
          sh 'docker tag  $REGISTRY_TEST/$DOCKER_NAMESPACE$APP_NAME:$VERSION_TEST-SNAPSHOT-$BUILD_NUMBER $REGISTRY_TEST/$DOCKER_NAMESPACE$APP_NAME:$VERSION_TEST'
          sh 'docker push  $REGISTRY_TEST/$DOCKER_NAMESPACE$APP_NAME:$VERSION_TEST'
        }
      }
    }

    stage('push latest for production') {
      when {
        branch env.BRANCH_PRODUCTION
      }
      steps {
        container('base') {
          withCredentials([usernamePassword(passwordVariable : 'AWS_IAM_ACCESS_ID' ,usernameVariable : 'AWS_ECR_USERNAME' ,credentialsId : "$AWS_ECR_CREDENTIAL_ID_PRODUCTION" ,)]) {
             withCredentials([usernamePassword(passwordVariable : 'AWS_IAM_ACCESS_KEY' ,usernameVariable : 'AWS_REGION' ,credentialsId : "$AWS_IAM_CREDENTIAL_ID_PRODUCTION" ,)]) {
                sh 'curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"'
                sh 'unzip awscliv2.zip'
                sh './aws/install'
                sh 'chmod a+x ./devops/set-aws-credentials.sh;./devops/set-aws-credentials.sh $AWS_IAM_ACCESS_ID $AWS_IAM_ACCESS_KEY $AWS_REGION'
                sh 'docker login $REGISTRY_PRODUCTION -u $AWS_ECR_USERNAME -p $(/usr/local/bin/aws ecr get-login-password --region $AWS_REGION)'
             }
          }
          sh 'docker tag  $REGISTRY_PRODUCTION/$DOCKER_NAMESPACE$APP_NAME:$VERSION_PRODUCTION-SNAPSHOT-$BUILD_NUMBER $REGISTRY_PRODUCTION/$DOCKER_NAMESPACE$APP_NAME:$VERSION_PRODUCTION'
          sh 'docker push  $REGISTRY_PRODUCTION/$DOCKER_NAMESPACE$APP_NAME:$VERSION_PRODUCTION'
        }
      }
    }

    stage('deploy for dev') {
      when {
        branch env.BRANCH_DEV
      }
      steps {
         container('base') {
            withCredentials([
                kubeconfigFile(
                credentialsId: env.DEV_KUBECONFIG_CREDENTIAL_ID,
                variable: 'KUBECONFIG')
                ]) {
                sh 'kubectl rollout restart -n $DEPLOY_NAMESPACE_DEV deployment/$DEPLOY_NAME'
            }
         }
      }
    }

    stage('deploy for test') {
      when {
        branch env.BRANCH_TEST
      }
      steps {
         container('base') {
            withCredentials([
                kubeconfigFile(
                credentialsId: env.TEST_KUBECONFIG_CREDENTIAL_ID,
                variable: 'KUBECONFIG')
                ]) {
                sh 'kubectl rollout restart -n $DEPLOY_NAMESPACE_TEST deployment/$DEPLOY_NAME'
            }
         }
      }
    }

    stage('deploy for production') {
      when {
        branch env.BRANCH_PRODUCTION
      }
      steps {
         container('base') {
            withCredentials([
                kubeconfigFile(
                credentialsId: env.PRODUCTION_KUBECONFIG_CREDENTIAL_ID,
                variable: 'KUBECONFIG')
                ]) {
                sh 'kubectl rollout restart -n $DEPLOY_NAMESPACE_PRODUCTION deployment/$DEPLOY_NAME'
            }
         }
      }
    }
  }

  post {
    always {
      echo 'One way or another, I have finished'
    }
    success {
       echo 'I succeeded!'
       echo "branch name: " + env.BRANCH_NAME
       script {
            if (env.BRANCH_NAME == env.BRANCH_DEV || env.BRANCH_NAME == env.BRANCH_TEST || env.BRANCH_NAME == env.BRANCH_PRODUCTION) {
                def mail_list = ['alexliang.kh@gmail.com','chenyulin@bisci.top','chaoyanghe.com@gmail.com','yideran@gmail.com','Yanfangli.fedml@gmail.com', 'zhouquan147369@gmail.com']
                mail_list.each { x ->
                    echo "mail item: ${x}"
                    mail (to: "${x}",
                          subject: env.FEDML_MAIL_SUCCESS_SUBJECT,
                          body: env.FEDML_MAIL_BODY1 + "${currentBuild.fullDisplayName}" + env.FEDML_MAIL_BODY2);
                }
            }
       }
    }
    unstable {
       echo 'I am unstable :/'
    }
    failure {
       echo 'I failed :('
       echo "branch name: " + env.BRANCH_NAME
       script {
            if (env.BRANCH_NAME == env.BRANCH_DEV || env.BRANCH_NAME == env.BRANCH_TEST || env.BRANCH_NAME == env.BRANCH_PRODUCTION) {
                def mail_list = ['alexliang.kh@gmail.com','chaoyanghe.com@gmail.com','yideran@gmail.com','Yanfangli.fedml@gmail.com', 'zhouquan147369@gmail.com']
                mail_list.each { x ->
                    echo "mail item: ${x}"
                    mail (to: "${x}",
                          subject: env.FEDML_MAIL_FAILURE_SUBJECT,
                          body: env.FEDML_MAIL_BODY1 + "${currentBuild.fullDisplayName}" + env.FEDML_MAIL_BODY2);
                }
            }
       }
    }
    changed {
       echo 'Things were different before...'
    }
  }
}
