/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    GlobalFooter: typeof import('./src/components/GlobalFooter.vue')['default']
    GlobalHeader: typeof import('./src/components/GlobalHeader.vue')['default']
    Press: typeof import('./src/components/Press.vue')['default']
    ProjectList: typeof import('./src/components/ProjectList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
