/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue')['BButton']
    BCol: typeof import('bootstrap-vue')['BCol']
    BForm: typeof import('bootstrap-vue')['BForm']
    BFormInput: typeof import('bootstrap-vue')['BFormInput']
    BFormSelect: typeof import('bootstrap-vue')['BFormSelect']
    BFormTextarea: typeof import('bootstrap-vue')['BFormTextarea']
    BIcon: typeof import('bootstrap-vue')['BIcon']
    BImg: typeof import('bootstrap-vue')['BImg']
    BImgLazy: typeof import('bootstrap-vue')['BImgLazy']
    BModal: typeof import('bootstrap-vue')['BModal']
    BottomJob: typeof import('./src/components/BottomJob.vue')['default']
    BPagination: typeof import('bootstrap-vue')['BPagination']
    BRow: typeof import('bootstrap-vue')['BRow']
    BSpinner: typeof import('bootstrap-vue')['BSpinner']
    BTab: typeof import('bootstrap-vue')['BTab']
    BTabs: typeof import('bootstrap-vue')['BTabs']
    CustomerAWS: typeof import('./src/components/CustomerAWS.vue')['default']
    CustomerDenso: typeof import('./src/components/CustomerDenso.vue')['default']
    CustomerEAIGLE: typeof import('./src/components/CustomerEAIGLE.vue')['default']
    CustomerJAIC: typeof import('./src/components/CustomerJAIC.vue')['default']
    CustomerKM: typeof import('./src/components/CustomerKM.vue')['default']
    CustomerLenovo: typeof import('./src/components/CustomerLenovo.vue')['default']
    CustomerSaftySpect: typeof import('./src/components/CustomerSaftySpect.vue')['default']
    CustomerTHETA: typeof import('./src/components/CustomerTHETA.vue')['default']
    CustomerVMware: typeof import('./src/components/CustomerVMware.vue')['default']
    GlobalFooter: typeof import('./src/components/GlobalFooter.vue')['default']
    GlobalHeader: typeof import('./src/components/GlobalHeader.vue')['default']
    Press: typeof import('./src/components/Press.vue')['default']
    Pricing: typeof import('./src/components/Pricing.vue')['default']
    PricingAiAgent: typeof import('./src/components/PricingAiAgent.vue')['default']
    PricingCompute: typeof import('./src/components/PricingCompute.vue')['default']
    PricingModel: typeof import('./src/components/PricingModel.vue')['default']
    PricingMonetization: typeof import('./src/components/PricingMonetization.vue')['default']
    PricingServerless: typeof import('./src/components/PricingServerless.vue')['default']
    ProductBeeHiveHowItWorks: typeof import('./src/components/ProductBeeHiveHowItWorks.vue')['default']
    ProductLLmHowItWorks: typeof import('./src/components/ProductLLmHowItWorks.vue')['default']
    ProductOctopusHowItWorks: typeof import('./src/components/ProductOctopusHowItWorks.vue')['default']
    ProductSpiderHowItWorks: typeof import('./src/components/ProductSpiderHowItWorks.vue')['default']
    ProjectList: typeof import('./src/components/ProjectList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UseCase: typeof import('./src/components/useCase.vue')['default']
    WhyFedML: typeof import('./src/components/WhyFedML.vue')['default']
  }
}
